import os
import sys
import re
import TEMPCSS


FINDUSERNAME = re.compile('(?:|)USERNAME(?:|\W)')
FINDUSERID = re.compile('(?:|)USERID(?:|\W)')
FINDUSERNODESIZE = re.compile('(?:|)USERNODESIZE(?:|\W)')
FINDUSERNODECOLOR = re.compile('(?:|)USERNODECOLOR(?:|\W)')
FINDUSERNODESHAPE = re.compile('(?:|)USERNODESHAPE(?:|\W)')
FINDUSERWAYWIDTH = re.compile('(?:|)USERWAYWIDTH(?:|\W)')
FINDUSERWAYCOLOR = re.compile('(?:|)USERWAYCOLOR(?:|\W)')
FINDNOTUPNODESIZE = re.compile('(?:|)NOTUPNODESIZE(?:|\W)')
FINDNOTUPNODECOLOR = re.compile('(?:|)NOTUPNODECOLOR(?:|\W)')
FINDNOTUPNODESHAPE = re.compile('(?:|)NOTUPNODESHAPE(?:|\W)')
FINDNOTUPWAYCOLOR = re.compile('(?:|)NOTUPWAYCOLOR(?:|\W)')
FINDNOTUPWAYWIDTH = re.compile('(?:|)NOTUPWAYWIDTH(?:|\W)')






USER1BLOCK = re.sub(FINDUSERNAME, 'Goose', TEMPCSS.USERBLOCK)
USER1BLOCK= re.sub(FINDUSERID, 'VLD154', USER1BLOCK)
USER1BLOCK= re.sub(FINDUSERNAME, 'Goose', USER1BLOCK)
USER1BLOCK = re.sub(FINDUSERNODESIZE, '15', USER1BLOCK)
USER1BLOCK= re.sub(FINDUSERNODECOLOR, 'blue', USER1BLOCK)
USER1BLOCK = re.sub(FINDUSERNODESHAPE, 'triangle', USER1BLOCK)
USER1BLOCK= re.sub(FINDUSERNAME, 'Goose', USER1BLOCK)
USER1BLOCK = re.sub(FINDUSERWAYWIDTH, '20', USER1BLOCK )
USER1BLOCK  = re.sub(FINDUSERWAYCOLOR, 'red', USER1BLOCK )

STATICBLOCK = re.sub(FINDNOTUPNODESIZE, '30', TEMPCSS.STATICBLOCK)
STATICBLOCK = re.sub(FINDNOTUPNODECOLOR, 'green', STATICBLOCK)
STATICBLOCK = re.sub(FINDNOTUPNODESHAPE, 'square', STATICBLOCK)
STATICBLOCK = re.sub(FINDNOTUPWAYCOLOR, 'green', STATICBLOCK)
STATICBLOCK = re.sub(FINDNOTUPWAYWIDTH, 'square', STATICBLOCK)

                       
print (str(USER1BLOCK))
print (str(STATICBLOCK))
